In [4]:
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.patches as mpatch
import seaborn as sns
import numpy as np
import pandas as pd

Güncel bir veri seti kullanıldı.
Kullandığımız bu kalp hastalığı veri seti Hindistan'daki çok uzmanlı hastanelerden birinden alındı.
Bu veri seti 12 özelliğe sahip 1000 denekten oluşmaktadır. Çok yönlü oluşu, erken evre kalp hastalığı tespiti ve tahmine dayalı makine öğrenimi modelleri oluşturmak için yararlı bir veri setidir.

In [9]:
base_url = "../data/cardiovascular_disease/"
cardiovascular_disease = base_url + "Cardiovascular_Disease_Dataset.csv"

In [10]:
cardio=pd.read_csv(cardiovascular_disease)

In [11]:
cardio.head()

,patientid,age,gender,chestpain,restingBP,serumcholestrol,fastingbloodsugar,restingrelectro,maxheartrate,exerciseangia,oldpeak,slope,noofmajorvessels,target
0,103368,53,1,2,171,0,0,1,147,0,5.3,3,3,1
1,119250,40,1,0,94,229,0,1,115,0,3.7,1,1,0
2,119372,49,1,2,133,142,0,0,202,1,5.0,1,0,0
3,132514,43,1,0,138,295,1,1,153,0,3.2,2,2,1
4,146211,31,1,1,199,0,0,2,136,0,5.3,3,2,1